import QueryProvider from "@/components/QueryProvider";
import "@mantine/carousel/styles.css";
import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/pagination";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ fontFamily: "'Nunito', sans-serif" }}>
        <QueryProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
